### ISSUE TITLE
[FEAT]: Ability to add full collections into filter

### ISSUE THREAD

**Issue by DanCrayons** [Tormak9970/TabMaster#127]
Hopefully this is already possible and I've missed something.

When looking in the steam default collections section you can see any collection you currently have and click into it.

When adding the collections to a new tab using TabMaster it seems to just dump what would be the contents of the collection if you were to click on it into that tab.

Is there a way to add the full collection that you can click to drill down into that specific collections list?

**Comment by jessebofill** [comment]
If you are asking whether it’s possible to have a custom tab display the square grid “collection” icons like the “collections” tab does then no it’s not and it’s not really how tab master is intended to work. It’s meant to create groupings or lists of games based on combining filters, and display their app grids in the tab page, just like all the default tabs do, with the exception of the “collections” tab. The filter types are merely meant to be used to determine what apps should be included in a tab and not dictate if the tab page should be displayed in a special way or sub categorized. The “collections” tab is a special kind of tab and it works in a different way than the other ones. Because of this it would make it difficult to implement what you’re asking into tab master and on top of that it wouldn’t really make sense how it should work, because for example some games that are included in a tab might not be in any collection. In my opinion I don’t think this would fit within the intended design of the plugin. Those are my thoughts but maybe tormak has something to say.

**Comment by Tormak9970** [comment]
@jessebofill summed it up well. The collections tab works differently then other tabs, and still has very poor performance, so we don't have any features related to it. Its also debateable whether its within the scope of TabMaster

**Comment by Tormak9970** [comment]
closing this. we will reopen if we decide to reconsider this feature
