### ISSUE TITLE
[BUG]: Metacritic Review Score filter not working correctly when combined with a filter for collections that show both Steam and non-Steam games

### ISSUE THREAD

**Issue by arvindhmani** [Tormak9970/TabMaster#185]
**Describe the bug**
When using the Metacritic Review Score filter in combination with a collection that shows all installed games on the device (both Steam and non-Steam), the tab only filters the Steam games in the collection that fulfill the criteria and excludes all non-Steam games.

**To Reproduce**
1. Create a dynamic collection in Steam. Under "Play State", check the "Installed locally" option. Save the collection.
2. Create a new tab
3. Add a filter using the dynamic collection ("Installed locally")
4. Add the Review Score filter and set it to any rating limit
5. Save the tab

**Expected behavior**
The tab shows all games installed on the system that satisfy the Review Score filter.

**Observed behavior**
The tab shows only the Steam games installed on the system that satisfy the Review Score filter.

**Enviroment Info:**
 - SteamOS Version: 3.5.17
 - SteamOS Update Channel: Stable
 - Decky Version: 2.11.1
 - Decky Update Channel: Stable
 - TabMaster Version: 2.5.4

**Comment by jessebofill** [comment]
This is not a bug, but expected behavior. Multiple filters are combined with Boolean logic “and” or “or”. By default it’s set to “and” which means a game has to meet the criteria of every filter set in order to be shown. If you change the combination logic to “or” it will show a game if it meets the criteria of any of the filters. So using “or” you should be able to achieve what you want.

**Comment by jessebofill** [comment]
To clarify. Steam games obviously don’t have a metacritic score, which is why they don’t meet the criteria of the metacritic filter.

**Comment by arvindhmani** [comment]
Ah okay, this is what I assumed. Thank you for clarifying. However as long as a game is named correctly, the Metacritic score should be obtainable no? Or is the metacritic score something that is tied to Steam itself?

**Comment by jessebofill** [comment]
> Ah okay, this is what I assumed. Thank you for clarifying. However as long as a game is named correctly, the Metacritic score should be obtainable no? Or is the metacritic score something that is tied to Steam itself?

Correct. Steam games have metacritic score associated with them automatically through steam as well as a bunch of other data, which is why a number of filters are only applicable to steam games specifically. We don’t do anything to modify games themselves. But if another plugin does modify non steam games to add certain properties then they should work, which I believe is the case with some game properties  through Emuchievements and Play Time.

**Comment by Tormak9970** [comment]
I did some research and there doesn't appear to be a way to fetch metacritic scores, so that would explain why

**Comment by arvindhmani** [comment]
Thank you for the clarification!
